@baseUrl = http://localhost:8080

GET {{baseUrl}}/categories
###
GET {{baseUrl}}/categories/page

###
GET  {{baseUrl}}/categories/4
###
GET {{baseUrl}}/categories/description/Mo%

###
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "description": "Teste"
}

###
PUT {{baseUrl}}/categories/4
Content-Type: application/json

{
    "description": "Lanches"
}

###
DELETE {{baseUrl}}/categories/3

###
GET {{baseUrl}}/transactions
###
GET {{baseUrl}}/transactions/page
###
GET  {{baseUrl}}/transactions/1
###
GET {{baseUrl}}/transactions/description/%Mec%
###
POST {{baseUrl}}/transactions
Content-Type: application/json

{
    "type": "EXPENSES",
    "date": "2020-10-11",
    "amount": 600.00,
    "description": "Teclado mecânico Logitec",
    "categoryId": 33
}
###
PUT {{baseUrl}}/transactions/3
Content-Type: application/json

{
    "type": "EXPENSES",
    "date": "2020-10-10",
    "amount": 20.00,
    "description": "Teclado Mecânico",
    "categoryId": 3
}
###
DELETE {{baseUrl}}/transactions/3