@baseUrl = http://localhost:8080

GET {{baseUrl}}/categories
###
GET {{baseUrl}}/categories/page

###
GET  {{baseUrl}}/categories/4

###
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "description": "Teste"
}

###
PUT {{baseUrl}}/categories/456
Content-Type: application/json

{
    "description": "Lanches"
}

###
DELETE {{baseUrl}}/categories/4

###
GET {{baseUrl}}/transactions
###
GET {{baseUrl}}/transactions/page
###
GET  {{baseUrl}}/transactions/12
###
POST {{baseUrl}}/transactions
Content-Type: application/json

{
    "type": "EXPENSES",
    "date": "2020-10-10",
    "amount": 30.00,
    "description": "Teclado Mecânico",
    "categoryId": 3
}