CREATE TABLE PROFILE (
	ID INT AUTO_INCREMENT,
	DESCRIPTION VARCHAR(80) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO PROFILE (DESCRIPTION) VALUES ('Admin');

CREATE TABLE USER (
	ID INT AUTO_INCREMENT,
	USERNAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO USER (USERNAME, PASSWORD) VALUES ('admin', '$2a$10$nUpWlnq.wcpdwo9B8MNimOpPIawTcUUZOzXHhlOQfxZG.GZehLxdG');

CREATE TABLE USER_PROFILES(
	USER_ID INT NOT NULL,
	PROFILES_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (PROFILES_ID) REFERENCES PROFILE(ID),
	PRIMARY KEY(USER_ID, PROFILES_ID)
);

INSERT INTO USER_PROFILES(USER_ID, PROFILES_ID) VALUES (1, 1);

CREATE TABLE CATEGORY (
	ID INT AUTO_INCREMENT, 
	DESCRIPTION VARCHAR(80) NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME,
	PRIMARY KEY(ID)
);

INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Motos', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Supermercado', CURRENT_TIMESTAMP());
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES ('Gadget', CURRENT_TIMESTAMP());

CREATE TABLE TRANSACTION (
	ID INT AUTO_INCREMENT,
	TYPE VARCHAR(10),
	DATE DATETIME NOT NULL,
    AMOUNT DECIMAL(9,2) NOT NULL,
    DESCRIPTION VARCHAR(80) NOT NULL,
    CATEGORY_ID INT NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME,
	PRIMARY KEY(ID),
    FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);
INSERT INTO TRANSACTION (TYPE, DATE, AMOUNT, DESCRIPTION, CATEGORY_ID, CREATED_AT) VALUES 
('EXPENSES', '2020/10/10', 20.00, 'Troca de óleo', 1, CURRENT_TIMESTAMP()),
('EXPENSES', '2020/10/10', 300.00, 'Compra Mensal', 2, CURRENT_TIMESTAMP());